sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - ./mvn-build-all.sh xml:check-format formatter:validate clean install jacoco:report
  - mvn -U coveralls:report -f terasoluna-gfw-parent/pom.xml
