sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - mvn -pl org.terasoluna.gfw:terasoluna-gfw xml:check-format
  - mvn formatter:validate -P common-libs
  - mvn -U clean install
  - mvn -U -P common-libs jacoco:report coveralls:report
