sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - mvn xml:check-format
  - find ./terasoluna-gfw-common-libraries -name "pom.xml" -type f -exec mvn formatter:validate -f {} \;
  - mvn -U clean install
  - mvn -U -P common-libs jacoco:report coveralls:report
