sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - find ./ -name "pom.xml" -type f -exec mvn formatter:validate -f {} \;
  - ./mvn-build-all.sh clean install jacoco:report
  - mvn -U coveralls:report -f terasoluna-gfw-parent/pom.xml
